name: Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

permissions:
  contents: write

env:
  PLUGIN_NAME: lidarr-spotify-plugin
  PLUGIN_VERSION: 1.0.0.${{ github.run_number }}

jobs:
  build-and-release:
    strategy:
      matrix:
        framework: [ net6.0 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build src/lidarr-spotify-plugin.sln --configuration Release

      - name: Upload net core
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.framework }}
          path: ./${{ env.PLUGIN_NAME }}.${{ matrix.framework }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: lidarr-spotify-plugin.zip
