name: Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

env:
  PLUGIN_NAME: lidarr-spotify-plugin
  PLUGIN_VERSION: 1.0.0
  MINIMUM_LIDARR_VERSION: 2.9.4.4538

jobs:
  build:
    strategy:
      matrix:
        framework: [ net6.0 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Publish
        run: dotnet publish src/lidarr-spotify-plugin.sln -c Release -f ${{ matrix.framework }}

      - name: Upload net core
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.framework }}
          path: ./publish/lidarr-spotify-plugin.zip
  publish:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact (net6.0)
        uses: actions/download-artifact@v4
        with:
          name: net6.0
          tag: v${{ env.PLUGIN_VERSION }}
          commitish: ${{ env.GITHUB_SHA }}
          name: Deemix Plugin
          body: >
            Lidarr plugin to add Deemix support

            Minimum Lidarr Version: ${{ env.MINIMUM_LIDARR_VERSION }}
          draft: true
          prerelease: true
          files: >
            ${{ env.PLUGIN_NAME }}.net6.0.zip
          gzip: false
